version: 0.2
proxy:
  upload-artifacts: yes
  logs: yes
 
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
       - python3 --version
       - apt-get install update
       - apt-get upgrade
       - npm install -g aws-cdk
       - apt-get install python3
       - python3 --version
       - pip3 install --upgrade pip
       - pip3 install -r requirements.txt 
  
  build:
    commands:
       - cdk diff
   