version: 0.2
proxy:
  upload-artifacts: yes
  logs: yes
 
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
       - apt-get install npm
       - npm install -g aws-cdk
       - apt-get install python3
       - pip install -r requirements.txt 
  
  build:
    commands:
       - cdk diff
   