version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
       - yum install nodejs
       - npm install -g aws-cdk
       - git install 
  
  build:
    commands:
       - command
       - command
  post_build:
    commands:
       - yum update
   